# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\"(\n\x16PeticionDescargarAudio\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"$\n\x13RespuestaChunkAudio\x12\r\n\x05\x64\x61tos\x18\x01 \x01(\x0c\x32R\n\rServicioAudio\x12\x41\n\x0e\x64\x65scargarAudio\x12\x17.PeticionDescargarAudio\x1a\x14.RespuestaChunkAudio0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PETICIONDESCARGARAUDIO']._serialized_start=15
  _globals['_PETICIONDESCARGARAUDIO']._serialized_end=55
  _globals['_RESPUESTACHUNKAUDIO']._serialized_start=57
  _globals['_RESPUESTACHUNKAUDIO']._serialized_end=93
  _globals['_SERVICIOAUDIO']._serialized_start=95
  _globals['_SERVICIOAUDIO']._serialized_end=177
# @@protoc_insertion_point(module_scope)
